'use strict';

/**
 * Tests for scripts/compliance/provision-anchor.js (stable anchor design).
 *
 * Run: node --test scripts/compliance/provision-anchor.test.js
 */

const test = require('node:test');
const assert = require('node:assert');
const { sha256Text, compactForHash, buildAnchor, hasPrimaryIdentity } = require('./provision-anchor.js');

test('sha256Text is deterministic and 64 hex chars', () => {
  const a = sha256Text('21. § (1) E törvény célja.');
  assert.match(a, /^[0-9a-f]{64}$/);
  assert.strictEqual(a, sha256Text('21. § (1) E törvény célja.'));
});

test('compactForHash collapses whitespace without affecting the excerpt semantic identity for hashing', () => {
  assert.strictEqual(compactForHash('  a \n b '), 'a b');
  assert.strictEqual(compactForHash('a  b'), 'a b');
});

test('buildAnchor produces a stable multi-part anchor with advisory lineSpan', () => {
  const anchor = buildAnchor({
    sourceKey: 'HU:ACT:1995:LIII',
    sourceSha256: 'deadbeef',
    provisionReference: '21. § (1)',
    heading: 'A környezet védelmének általános szabályai',
    lineStart: 120,
    lineEnd: 122,
    excerpt: '21. § (1) E törvény célja a környezet védelmének általános szabályainak meghatározása.',
  });
  assert.strictEqual(anchor.sourceKey, 'HU:ACT:1995:LIII');
  assert.strictEqual(anchor.provisionReference, '21. § (1)');
  assert.deepStrictEqual(anchor.lineSpan, { start: 120, end: 122 });
  assert.match(anchor.excerptSha256, /^[0-9a-f]{64}$/);
  assert.strictEqual(hasPrimaryIdentity(anchor), true);
});

test('hasPrimaryIdentity is false when a primary field is missing', () => {
  assert.strictEqual(hasPrimaryIdentity(buildAnchor({ sourceKey: 'K', sourceSha256: 'S' })), false);
});

test('same excerpt and reference yield the same excerptSha256 regardless of line number', () => {
  const excerpt = '1. § E törvény célja.';
  const a = buildAnchor({ sourceKey: 'K', sourceSha256: 'S', provisionReference: '1. §', lineStart: 1, lineEnd: 1, excerpt });
  const b = buildAnchor({ sourceKey: 'K', sourceSha256: 'S', provisionReference: '1. §', lineStart: 900, lineEnd: 900, excerpt });
  assert.strictEqual(a.excerptSha256, b.excerptSha256);
});

test('no legal claim is generated by the anchor builder', () => {
  const anchor = buildAnchor({ sourceKey: 'K', sourceSha256: 'S', provisionReference: '1. §', excerpt: 'x' });
  assert.ok(!('obligation' in anchor));
  assert.ok(!('applicability' in anchor));
  assert.ok(!('requirement' in anchor));
});
