/**
 * DW0 — provider-neutral binary object storage.
 *
 * This interface deliberately knows NOTHING about Case / Document /
 * DocumentVersion / Client. It is a dumb byte container:
 *
 *   put(byte payload)  -> opaque storage reference
 *   get(opaque ref)    -> exact original bytes (or null if absent)
 *   delete(opaque ref) -> whether the object was removed
 *   exists(opaque ref) -> whether the object is present
 *   metadata(opaque ref, optional) -> optional implementation metadata
 *
 * The storage reference is OPAQUE: it is always generated by the provider on
 * `put` and returned to the caller. Callers never supply a path, so the
 * reference cannot be used to traverse a filesystem or reach an unintended
 * object.
 */

export interface StorageObjectMeta {
  mimeType?: string | null;
  size?: number | null;
}

export interface PutResult {
  /** Opaque storage reference; never caller-controlled. */
  reference: string;
  size: number;
}

export interface BinaryObjectStorage {
  put(data: Buffer, meta?: StorageObjectMeta): Promise<PutResult>;
  /** Returns the exact stored bytes, or null when the object does not exist. */
  get(reference: string): Promise<Buffer | null>;
  /** Returns true when the object was removed (or was already absent). */
  delete(reference: string): Promise<boolean>;
  exists(reference: string): Promise<boolean>;
  /** Optional implementation metadata; returns null when unavailable. */
  metadata?(reference: string): Promise<StorageObjectMeta | null>;
}

/**
 * A storage reference is a UUID (v4). Anything else is rejected so a caller
 * can never influence the underlying object location. This is the single
 * path-traversal / injection guard shared by every adapter.
 */
const OPACQUE_REFERENCE_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isOpaqueStorageReference(reference: unknown): reference is string {
  return typeof reference === 'string' && OPACQUE_REFERENCE_RE.test(reference);
}

export function assertOpaqueStorageReference(reference: unknown): string {
  if (!isOpaqueStorageReference(reference)) {
    throw new StorageReferenceError('Invalid or non-opaque storage reference.');
  }
  return reference;
}

export class StorageReferenceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'StorageReferenceError';
  }
}

export class StorageWriteError extends Error {
  constructor(
    public readonly operation: 'put' | 'delete' | 'get',
    message: string,
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'StorageWriteError';
  }
}