import clientPortalRouter from '../src/routes/clientPortal';
import workReportRouter from '../src/modules/work-reports/routes';
import { writeFileSync, mkdirSync } from 'fs';
import {randomUUID} from 'crypto';
import express from 'express';
import type {Server} from 'http';
import {prisma} from '../src/prisma/prisma.service';
import {historyPolicyRouter} from '../src/modules/case-history/policy.routes';
import {createGrant,transitionGrant,createMatterPublication,submitMatterPublication,approveMatterPublication,publishMatterPublication,getPortalMatter} from '../src/modules/client-publication/publicationService';
import {reportHistory} from '../src/modules/case-history/policy.service';
jest.mock('../src/middleware/auth',()=>({authenticate:(req:any,_res:any,next:any)=>{req.user={userId:req.headers['x-test-user'],role:req.headers['x-test-role']||'ADMIN'};next()}}));
jest.mock('../src/middleware/clientPortalAuth',()=>({...jest.requireActual('../src/middleware/clientPortalAuth'),authenticateClientPortal:(req:any,_res:any,next:any)=>{req.clientPortalSession={identityType:'CLIENT_PORTAL',clientPortalIdentityId:req.headers['x-test-portal'],normalizedEmail:req.headers['x-test-portal']+'@wf10.invalid',displayName:'Synthetic portal identity',accountType:'INDIVIDUAL',status:'ACTIVE',emailVerified:true,sessionContext:'CUSTOMER_IDENTITY_PROVIDER'};next()}}));
const manager=randomUUID(),customer=randomUUID(),client=randomUUID(),caseId=randomUUID(),eventId=randomUUID();
let server:Server,base:string,grantId:string,publicationId:string,policy:any,snapshot:any;
const internal={userId:manager,role:'ADMIN'};const portal={userId:customer,role:'CLIENT'};
beforeAll(async()=>{
 const url=new URL(process.env.DATABASE_URL||'');if(url.hostname!=='127.0.0.1'||url.port!=='55483'||url.pathname!=='/adminiculum_replay_wf10')throw Error('Unsafe test DB');
 const identity=await prisma.$queryRaw<any[]>`SELECT current_database() db,current_user usr,inet_server_port() port`;expect(identity[0]).toMatchObject({db:'adminiculum_replay_wf10',usr:'wf10_pgtest',port:55483});
 process.env.ENABLE_CUSTOMER_HISTORY_POLICY='true';process.env.CLIENT_PORTAL_READ_ENABLED='true';
 await prisma.user.createMany({data:[{id:manager,email:`${manager}@wf10.invalid`,name:'Manager',role:'ADMIN',skills:[]},{id:customer,email:`${customer}@wf10.invalid`,name:'Customer',role:'CLIENT',skills:[]}]});
 await prisma.client.create({data:{id:client,name:'Synthetic history client'}});
 await prisma.case.create({data:{id:caseId,caseNumber:caseId,title:'RAW_PRIVATE_CASE',clientId:client,caseType:'OTHER',createdById:manager}});
 await prisma.timelineEvent.create({data:{id:eventId,caseId,eventType:'CUSTOM',description:'RAW_PRIVATE_EVENT',userId:manager}});
 const grant=await createGrant(internal,{caseId,clientId:client,clientUserId:customer,validFrom:'2026-01-01T00:00:00Z',permissions:['MATTER_READ','DOCUMENT_READ','UPDATE_READ']},prisma);grantId=grant.id;await transitionGrant(internal,grantId,'activate',{expectedRevision:grant.revision},prisma);
 const draft=await createMatterPublication(internal,{caseId,clientSafeTitle:'Safe synthetic case',clientSafeStatus:'Folyamatban',clientSafeNextStep:'Következő lépés'},prisma);publicationId=draft.id;
 const submitted=await submitMatterPublication(internal,draft.id,{expectedRevision:draft.revision},prisma);const approved=await approveMatterPublication(internal,draft.id,{expectedRevision:submitted.revision},prisma);await publishMatterPublication(internal,draft.id,{expectedRevision:approved.revision},prisma);
 await prisma.clientSafeUpdate.create({data:{caseId,clientId:client,title:'Published update',body:'Published safe content',category:'GENERAL',status:'PUBLISHED',preparedById:manager,approvedById:manager,publishedById:manager,publishedAt:new Date(),audienceSnapshot:{}} as any});
 const app=express();app.use(express.json());app.use('/portal',clientPortalRouter);app.use('/reports',workReportRouter);app.use(historyPolicyRouter);await new Promise<void>(r=>{server=app.listen(0,'127.0.0.1',()=>r())});base=`http://127.0.0.1:${(server.address() as any).port}/cases/${caseId}/policy`;
},30000);
afterAll(async()=>{if(server)await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect()});
async function call(suffix='',method='GET',body?:unknown){const r=await fetch(base+suffix,{method,headers:{'content-type':'application/json','x-test-user':manager},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json() as any}}
async function save(s:any){const r=await call('','PUT',{revision:policy.revision,snapshot:s});expect(r.status).toBe(200);policy=r.body;snapshot=s;}
async function publish(){let r=await call('/review','POST',{revision:policy.revision});expect(r.status).toBe(200);policy=r.body;r=await call('/publish','POST',{revision:policy.revision});expect(r.status).toBe(200);policy=r.body;}
test('no policy adds no data and retains baseline published content',async()=>{const matter=await getPortalMatter(portal,publicationId,prisma);expect(matter.history.items).toEqual([]);expect(matter.updates.length).toBe(1);expect(await reportHistory(caseId,client,{startDate:null,endDate:null},prisma)).toBeNull();policy=(await call(`?grantId=${grantId}&publicationId=${publicationId}`)).body;expect(policy.sources.some((s:any)=>s.sourceKey===`timeline:${eventId}`)).toBe(true);});
test('draft remains private, explicit review required, level 1 releases only status',async()=>{await save({level:1,audienceGrantId:grantId,publicationId,overlays:[]});expect((await getPortalMatter(portal,publicationId,prisma)).history.items).toEqual([]);expect((await call('/publish','POST',{revision:policy.revision})).status).toBe(409);await publish();const m=await getPortalMatter(portal,publicationId,prisma);expect(m.history.items.length).toBeGreaterThan(0);expect(JSON.stringify(m.history)).not.toContain('Published safe content');expect(JSON.stringify(m.history)).not.toContain('RAW_PRIVATE_EVENT');});
test('level 2 and portal/report projection are identical at common source set and period',async()=>{await save({...snapshot,level:2});await publish();const m=await getPortalMatter(portal,publicationId,prisma);const r=await reportHistory(caseId,client,{startDate:null,endDate:null},prisma);expect(m.history.items).toEqual(r!.items);expect(m.history.policyRevision).toBe(r!.policyRevision);expect(m.history.sourceSetDigest).toBe(r!.sourceSetDigest);expect(JSON.stringify(m.history)).toContain('Published safe content');expect(m.updates).toEqual([]);});
test('level 3 requires reviewed safe narrative and never returns raw event IDs or text',async()=>{const source=policy.sources.find((s:any)=>s.sourceKey===`timeline:${eventId}`);await save({...snapshot,level:3,overlays:[{sourceKey:source.sourceKey,sourceRevision:source.sourceRevision,excluded:false,customerText:'Reviewed safe narrative',includeTime:false}]});expect(JSON.stringify((await getPortalMatter(portal,publicationId,prisma)).history)).not.toContain('Reviewed safe narrative');await publish();const serialized=JSON.stringify((await getPortalMatter(portal,publicationId,prisma)).history);expect(serialized).toContain('Reviewed safe narrative');for(const marker of ['RAW_PRIVATE_EVENT',eventId,'payload','description'])expect(serialized).not.toContain(marker);});
test('real HTTP report preview and PDF use the same long reviewed history',async()=>{
 const source=policy.sources.find((s:any)=>s.sourceKey===`timeline:${eventId}`);
 await save({...snapshot,overlays:[{sourceKey:source.sourceKey,sourceRevision:source.sourceRevision,excluded:false,customerText:('Hosszú, ellenőrzött ügyféltájékoztatás a dokumentum feldolgozásáról. ').repeat(40),includeTime:false}]});await publish();
 const issuer={legalName:'WF10 Szintetikus Ügyvédi Iroda',address:'Teszt utca 1.',taxNumber:'TEST-NOT-REAL'};
 await prisma.systemSetting.upsert({where:{key:'billing.issuerProfile'},create:{key:'billing.issuerProfile',value:issuer},update:{value:issuer}});
 const origin=new URL(base).origin;const preview=await fetch(`${origin}/reports/cases/${caseId}`,{headers:{'x-test-user':manager}});expect(preview.status).toBe(200);const dto=await preview.json() as any;const portalHistory=(await getPortalMatter(portal,publicationId,prisma)).history;expect(dto.exportPreview.historyProvenance).toEqual({policyRevision:portalHistory.policyRevision,sourceSetDigest:portalHistory.sourceSetDigest});expect(dto.exportPreview.safeUpdates.some((i:any)=>i.body.includes('Hosszú, ellenőrzött'))).toBe(true);
 const response=await fetch(`${origin}/reports/cases/${caseId}/pdf`,{headers:{'x-test-user':manager}});expect(response.status).toBe(200);expect(response.headers.get('content-type')).toContain('application/pdf');const bytes=Buffer.from(await response.arrayBuffer());expect(bytes.subarray(0,4).toString()).toBe('%PDF');mkdirSync('../work/evidence',{recursive:true});writeFileSync('../work/evidence/wf10-real-route-report.pdf',bytes);writeFileSync('../work/evidence/wf10-report-preview.json',JSON.stringify(dto.exportPreview,null,2));
});
test('exclusion persists across level changes, drafts do not mutate active text',async()=>{const o=snapshot.overlays[0];await save({...snapshot,overlays:[{...o,excluded:true,customerText:'New draft text'}]});expect(JSON.stringify((await getPortalMatter(portal,publicationId,prisma)).history)).toContain('Hosszú, ellenőrzött');await publish();await save({...snapshot,level:2});await publish();await save({...snapshot,level:3});await publish();expect(JSON.stringify((await getPortalMatter(portal,publicationId,prisma)).history)).not.toContain('New draft text');});
test('conflicting editors and changed source revisions fail closed',async()=>{expect((await call('','PUT',{revision:0,snapshot})).status).toBe(409);const old=snapshot.overlays[0];await prisma.timelineEvent.update({where:{id:eventId},data:{description:'CHANGED_PRIVATE_EVENT'}});expect((await call('','PUT',{revision:policy.revision,snapshot:{...snapshot,overlays:[{...old,excluded:false}]}})).status).toBe(409);});
test('actual portal router enforces active identity workspace and grant with report parity',async()=>{
 const identity=await prisma.clientPortalIdentity.create({data:{provider:'ENTRA_EXTERNAL_ID',issuer:'wf10.invalid',subject:randomUUID(),normalizedEmail:randomUUID()+'@wf10.invalid',displayName:'Synthetic portal reader',accountType:'INDIVIDUAL',status:'ACTIVE',emailVerifiedAt:new Date()}});
 const workspace=await prisma.clientPortalWorkspace.create({data:{clientId:client,name:'Synthetic test workspace',mode:'INDIVIDUAL',publicReference:randomUUID(),createdById:manager}});
 const membership=await prisma.clientPortalWorkspaceMembership.create({data:{clientPortalIdentityId:identity.id,workspaceId:workspace.id,status:'ACTIVE',approvedById:manager,approvedAt:new Date()}});
 const grant=await createGrant(internal,{caseId,clientId:client,clientPortalIdentityId:identity.id,workspaceId:workspace.id,validFrom:'2026-01-01T00:00:00Z',permissions:['MATTER_READ','DOCUMENT_READ','UPDATE_READ']},prisma);await transitionGrant(internal,grant.id,'activate',{expectedRevision:grant.revision},prisma);
 const oldSnapshot=snapshot;await save({...snapshot,audienceGrantId:grant.id,overlays:[]});await publish();
 const url=new URL(base).origin+'/portal/matters/'+publicationId;const headers={'x-test-portal':identity.id,'x-client-portal-workspace':workspace.publicReference};
 const response=await fetch(url,{headers});expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');const dto=await response.json() as any;expect(dto.history.items).toEqual((await reportHistory(caseId,client,{startDate:null,endDate:null},prisma))!.items);
 await prisma.clientPortalWorkspaceMembership.update({where:{id:membership.id},data:{status:'SUSPENDED'}});expect((await fetch(url,{headers})).status).toBe(403);expect((await reportHistory(caseId,client,{startDate:null,endDate:null},prisma))!.items).toEqual([]);
 await save(oldSnapshot);await publish();
});
test('withdrawal suppresses future managed reads without recalling downloads',async()=>{const r=await call('/withdraw','POST',{revision:policy.revision});expect(r.status).toBe(200);expect((await getPortalMatter(portal,publicationId,prisma)).history.items).toEqual([]);expect((await reportHistory(caseId,client,{startDate:null,endDate:null},prisma))!.items).toEqual([]);});
test('revoked audience grant fails future reads',async()=>{await prisma.clientPortalGrant.update({where:{id:grantId},data:{status:'REVOKED'}});await expect(getPortalMatter(portal,publicationId,prisma)).rejects.toThrow();});
