import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  DW0_MAX_DOCUMENT_UPLOAD_BYTES,
  DW0_BASE64_ENVELOPE_BYTES,
  base64EnvelopeWithinLimit,
} from '../src/modules/storage/policy';

const repoRoot = path.join(__dirname, '..', '..');
const read = (p: string): string => fs.readFileSync(path.join(repoRoot, p), 'utf8');

const servicePath = 'Backend/src/modules/documents/services.ts';
const routesPath = 'Backend/src/modules/documents/routes.ts';
const driveServicePath = 'Backend/src/modules/sharepoint/driveService.ts';
const graphClientPath = 'Backend/src/modules/sharepoint/graphClient.ts';
const sharepointAdapterPath = 'Backend/src/modules/storage/sharepointAdapter.ts';
const interfacePath = 'Backend/src/modules/storage/interface.ts';

describe('Phase DW0 hardening — schema-free storage safety', () => {
  it('routes production PUT through the BinaryObjectStorage interface (no direct driveService upload)', () => {
    const services = read(servicePath);
    const putDocumentBytes = services.slice(
      services.indexOf('async function putDocumentBytes'),
      services.indexOf('class DocumentsService'),
    );

    expect(putDocumentBytes).toContain('getDocumentStorage().put');
    expect(putDocumentBytes).toContain('storageReference: put.reference');
    // The caller must never supply a path/reference — only advisory placement meta.
    expect(putDocumentBytes).not.toContain('driveService.uploadDocument');
    expect(putDocumentBytes).not.toMatch(/reference:\s*input\./);
  });

  it('uses the correct Microsoft Graph DELETE verb and endpoint for drive items', () => {
    const drive = read(driveServicePath);
    const graph = read(graphClientPath);

    // DriveItem removal is `DELETE /sites/{siteId}/drive/items/{itemId}` — not a
    // POST to a `/delete` suffix.
    expect(drive).toContain('graphClient.delete(');
    expect(drive).toContain('drive/items/${documentId}');
    expect(drive).not.toContain('drive/items/${documentId}/delete');

    expect(graph).toContain("method: 'DELETE'");
    expect(graph).toContain("async delete<T = unknown>");
  });

  it('keeps the storage reference provider-opaque and caller-independent', () => {
    const iface = read(interfacePath);
    const adapter = read(sharepointAdapterPath);

    // The reference is always generated by the provider on put, never supplied.
    expect(iface).toContain('OPACQUE_REFERENCE_RE');
    expect(iface).toContain('assertOpaqueStorageReference');
    // SharePoint adapter returns the DriveItem id as the opaque reference.
    expect(adapter).toContain('reference: result.item.id');
  });

  it('never silently swallows upload compensation failures', () => {
    const services = read(servicePath);

    expect(services).toContain('compensateFailedUpload(');
    expect(services).toContain('upload compensation FAILED');
    // No silent `.catch(() => false)` compensation remains.
    const compensationBlock = services.slice(
      services.indexOf('async function compensateFailedUpload'),
      services.indexOf('class DocumentsService'),
    );
    expect(compensationBlock).toContain('getDocumentStorage().delete');
    expect(services).not.toContain('getDocumentStorage().delete(putBytes.storageReference).catch');
  });

  it('rejects an oversized base64 payload from its string length before decode', () => {
    // The envelope is strictly larger than the decoded binary cap, so the guard
    // rejects by string length before any Buffer expansion.
    expect(DW0_BASE64_ENVELOPE_BYTES).toBeGreaterThan(DW0_MAX_DOCUMENT_UPLOAD_BYTES);

    const atLimit = 'A'.repeat(DW0_BASE64_ENVELOPE_BYTES);
    const overLimit = 'A'.repeat(DW0_BASE64_ENVELOPE_BYTES + 1);

    expect(base64EnvelopeWithinLimit(atLimit)).toBe(true);
    expect(base64EnvelopeWithinLimit(overLimit)).toBe(false);
    expect(base64EnvelopeWithinLimit(12345)).toBe(false);
    expect(base64EnvelopeWithinLimit(null)).toBe(false);
  });

  it('wires the pre-decode rejection into every upload route before Buffer expansion', () => {
    const routes = read(routesPath);

    const createRoute = routes.slice(routes.indexOf("router.post('/', authenticate"), routes.indexOf("router.get('/case/"));
    const versionsRoute = routes.slice(routes.indexOf("router.post('/:id/versions'"), routes.indexOf("router.get('/:id/versions/:versionId'"));
    const legacyRoute = routes.slice(routes.indexOf("router.post('/:id/version'"), routes.indexOf("router.post('/:id/submit-review'"));

    expect(createRoute).toContain('base64PayloadTooLarge');
    expect(versionsRoute).toContain('base64PayloadTooLarge');
    expect(legacyRoute).toContain('base64PayloadTooLarge');
    expect(routes).toContain("code: 'DOCUMENT_TOO_LARGE'");
  });
});
