/**
 * GWO-1 — Funding & Tenders request layer.
 *
 * Only the official search endpoint construction, a bounded POST request,
 * timeout, and bounded transient retry live here. No normalization logic and
 * absolutely no customer/client/case fields.
 *
 * Official live portal contract (recovered from the portal runtime and proven
 * live on 2026-09-27, outside the portal):
 * - POST https://api.tech.ec.europa.eu/search-api/prod/rest/search?apiKey=SEDIA
 * - URL query: text=*** & pageSize=<bounded> & pageNumber=<n>
 * - multipart/form-data body (fetch/FormData generates the boundary; the
 *   Content-Type header is NEVER set manually) with JSON Blob parts:
 *     sort:      {"order":"DESC","field":"startDate"}
 *     query:     bool.must = [ type ["1","2","8"], status [3 lifecycle codes],
 *                             DATASOURCE ["SEDIA"], language ["en"] ]
 *     languages: ["en"]
 * - Proven result: HTTP 200 with 5/5 DATASOURCE=SEDIA records carrying
 *   authoritative metadata.identifier funding topic records.
 */

export const FUNDING_TENDERS_SEARCH_URL =
  'https://api.tech.ec.europa.eu/search-api/prod/rest/search?apiKey=SEDIA';

export const DEFAULT_TIMEOUT_MS = 30_000;
export const DEFAULT_MAX_RETRIES = 2;
export const DEFAULT_PAGE_SIZE = 10;
export const MAX_PAGE_SIZE = 50;
export const MAX_RESPONSE_BYTES = 10 * 1024 * 1024;

/** Official portal defaults for the calls-for-proposals (funding) discovery. */
export const DEFAULT_SEARCH_TEXT = '***';
export const FUNDING_SOURCE_TYPES = ['1', '2', '8'] as const;
export const FUNDING_LIFECYCLE_STATUSES = ['31094501', '31094502', '31094503'] as const;
export const FUNDING_DATASOURCE = ['SEDIA'] as const;
export const DISCOVERY_LANGUAGE = 'en';
export const DISCOVERY_SORT = { order: 'DESC', field: 'startDate' } as const;

export interface SearchRequestOptions {
  /** Full-text query. Default "***" per the official portal contract. */
  text?: string;
  pageSize?: number;
  pageNumber?: number;
  timeoutMs?: number;
  maxRetries?: number;
  /** Overridable for deterministic tests; defaults to the official endpoint. */
  url?: string;
}

/** Official calls-for-proposals discovery query (verbatim portal shape). */
export function buildDiscoveryQuery(): Record<string, unknown> {
  return {
    bool: {
      must: [
        { terms: { type: [...FUNDING_SOURCE_TYPES] } },
        { terms: { status: [...FUNDING_LIFECYCLE_STATUSES] } },
        { terms: { DATASOURCE: [...FUNDING_DATASOURCE] } },
        { terms: { language: [DISCOVERY_LANGUAGE] } },
      ],
    },
  };
}

export function buildDiscoverySort(): Record<string, unknown> {
  return { order: DISCOVERY_SORT.order, field: DISCOVERY_SORT.field };
}

/** Full request URL with the official query parameters. */
export function buildDiscoveryUrl(options: Pick<SearchRequestOptions, 'text' | 'pageSize' | 'pageNumber' | 'url'> = {}): string {
  const pageSize = options.pageSize ?? DEFAULT_PAGE_SIZE;
  const pageNumber = options.pageNumber ?? 1;
  const base = options.url ?? FUNDING_TENDERS_SEARCH_URL;
  const separator = base.includes('?') ? '&' : '?';
  const params = new URLSearchParams({
    text: options.text ?? DEFAULT_SEARCH_TEXT,
    pageSize: String(pageSize),
    pageNumber: String(pageNumber),
  });
  return `${base}${separator}${params.toString()}`;
}

/**
 * multipart/form-data body with JSON Blob parts. The multipart boundary and
 * Content-Type are generated by fetch/FormData — never set manually.
 */
export function buildDiscoveryFormData(): FormData {
  const form = new FormData();
  form.append('sort', new Blob([JSON.stringify(buildDiscoverySort())], { type: 'application/json' }));
  form.append('query', new Blob([JSON.stringify(buildDiscoveryQuery())], { type: 'application/json' }));
  form.append('languages', new Blob([JSON.stringify([DISCOVERY_LANGUAGE])], { type: 'application/json' }));
  return form;
}

export interface SearchResultEntry {
  reference: string;
  url: string | null;
  contentType: string | null;
  language: string | null;
  databaseLabel: string | null;
  summary: string | null;
  content: string | null;
  checksum: string | null;
  /** ES-stored document metadata (values are scalars or arrays). */
  metadata: Record<string, unknown>;
}

export interface SearchResponseEnvelope {
  apiVersion: string;
  terms: string | null;
  totalResults: number | null;
  pageNumber: number | null;
  pageSize: number | null;
  sort: string | null;
  results: SearchResultEntry[];
}

export type RequestErrorCode =
  | 'INVALID_ARGUMENT'
  | 'HTTP_ERROR'
  | 'TIMEOUT'
  | 'NETWORK_ERROR'
  | 'SIZE_EXCEEDED'
  | 'MALFORMED_RESPONSE'
  | 'RETRIES_EXHAUSTED';

export class FundingTendersRequestError extends Error {
  readonly code: RequestErrorCode;
  readonly status: number | null;

  constructor(code: RequestErrorCode, message: string, status: number | null = null) {
    super(message);
    this.name = 'FundingTendersRequestError';
    this.code = code;
    this.status = status;
  }
}

const RETRYABLE_HTTP = new Set([408, 425, 429, 500, 502, 503, 504]);

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function firstScalar(value: unknown): string | null {
  if (Array.isArray(value)) {
    return firstScalar(value[0]);
  }
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  return null;
}

function parseEnvelope(text: string): SearchResponseEnvelope {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new FundingTendersRequestError('MALFORMED_RESPONSE', 'Search response is not valid JSON.');
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new FundingTendersRequestError('MALFORMED_RESPONSE', 'Search response is not a JSON object.');
  }
  const row = parsed as Record<string, unknown>;
  const rawResults = Array.isArray(row.results) ? row.results : [];
  const results: SearchResultEntry[] = rawResults.map((entry) => {
    const item = (entry ?? {}) as Record<string, unknown>;
    const meta = item.metadata !== null && typeof item.metadata === 'object' ? (item.metadata as Record<string, unknown>) : {};
    return {
      reference: firstScalar(item.reference) ?? '',
      url: firstScalar(item.url),
      contentType: firstScalar(item.contentType),
      language: firstScalar(item.language),
      databaseLabel: firstScalar(item.databaseLabel),
      summary: firstScalar(item.summary),
      content: firstScalar(item.content),
      checksum: firstScalar(item.checksum),
      metadata: meta,
    };
  });
  return {
    apiVersion: firstScalar(row.apiVersion) ?? 'unknown',
    terms: firstScalar(row.terms),
    totalResults: typeof row.totalResults === 'number' ? row.totalResults : null,
    pageNumber: typeof row.pageNumber === 'number' ? row.pageNumber : null,
    pageSize: typeof row.pageSize === 'number' ? row.pageSize : null,
    sort: firstScalar(row.sort),
    results,
  };
}

/**
 * One bounded search execution. Transient failures (network, timeout, 408/429/5xx)
 * are retried with exponential backoff; other 4xx responses fail immediately.
 * Never sends any customer/client/case data.
 */
export async function executeFundingTendersSearch(options: SearchRequestOptions = {}): Promise<SearchResponseEnvelope> {
  const pageSize = options.pageSize ?? DEFAULT_PAGE_SIZE;
  const pageNumber = options.pageNumber ?? 1;
  if (!Number.isInteger(pageSize) || pageSize < 1 || pageSize > MAX_PAGE_SIZE) {
    throw new FundingTendersRequestError('INVALID_ARGUMENT', `pageSize must be an integer in [1, ${MAX_PAGE_SIZE}].`);
  }
  if (!Number.isInteger(pageNumber) || pageNumber < 1) {
    throw new FundingTendersRequestError('INVALID_ARGUMENT', 'pageNumber must be a positive integer.');
  }
  const timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const maxRetries = options.maxRetries ?? DEFAULT_MAX_RETRIES;
  const requestUrl = buildDiscoveryUrl(options);
  const headers: Record<string, string> = {
    accept: 'application/json',
    'user-agent': 'adminiculum-opportunity-watcher/0.1 (bounded manual dry-run; internal)',
  };

  let lastError: FundingTendersRequestError | null = null;
  for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
    if (attempt > 0) {
      await sleep(1000 * 2 ** (attempt - 1));
    }
    try {
      const response = await fetch(requestUrl, {
        method: 'POST',
        headers,
        body: buildDiscoveryFormData(),
        signal: AbortSignal.timeout(timeoutMs),
      });
      const declaredLength = Number(response.headers.get('content-length') ?? '0');
      if (declaredLength > MAX_RESPONSE_BYTES) {
        throw new FundingTendersRequestError('SIZE_EXCEEDED', 'Search response exceeds the bounded size limit.');
      }
      const text = await response.text();
      if (text.length > MAX_RESPONSE_BYTES) {
        throw new FundingTendersRequestError('SIZE_EXCEEDED', 'Search response exceeds the bounded size limit.');
      }
      if (!response.ok) {
        const err = new FundingTendersRequestError('HTTP_ERROR', `Search request failed with HTTP ${response.status}.`, response.status);
        lastError = err;
        if (RETRYABLE_HTTP.has(response.status)) {
          continue;
        }
        throw err;
      }
      return parseEnvelope(text);
    } catch (error) {
      if (error instanceof FundingTendersRequestError) {
        if (error.code === 'HTTP_ERROR' && error.status !== null && RETRYABLE_HTTP.has(error.status)) {
          lastError = error;
          continue;
        }
        throw error;
      }
      const name = error instanceof Error ? error.name : 'Unknown';
      if (name === 'TimeoutError' || name === 'AbortError') {
        lastError = new FundingTendersRequestError('TIMEOUT', `Search request timed out after ${timeoutMs} ms.`);
        continue;
      }
      lastError = new FundingTendersRequestError('NETWORK_ERROR', 'Search request failed: network error.');
      continue;
    }
  }
  throw lastError ?? new FundingTendersRequestError('RETRIES_EXHAUSTED', 'Search request failed after all retry attempts.');
}

// ---------------------------------------------------------------------------
// Official static topicDetails enrichment fetch (GWO-1G).
//
// GET https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/<identifier>.json
// Enrichment only: obtains the official topic update history used for the
// source order signal. No cookies, no auth, no customer data. One transient
// retry maximum; 30 s timeout; bounded response size.
// ---------------------------------------------------------------------------

export const TOPIC_DETAILS_URL_PREFIX =
  'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/';

export const DETAIL_TIMEOUT_MS = 30_000;
export const DETAIL_MAX_RETRIES = 1;
export const DETAIL_MAX_RESPONSE_BYTES = 2 * 1024 * 1024;

export interface TopicDetailsFetchOptions {
  timeoutMs?: number;
  maxRetries?: number;
  /** Overridable for deterministic tests; defaults to the official prefix. */
  urlPrefix?: string;
  /** Test-only fetch injection; defaults to global fetch. */
  fetchImpl?: typeof fetch;
}

/**
 * One bounded official topicDetails GET. Returns the parsed raw JSON object
 * (expected shape { TopicDetails: { ... } }); identity validation happens in
 * the enrichment layer, never here. Fails with deterministic error codes.
 */
export async function fetchOfficialTopicDetails(
  identifier: string,
  options: TopicDetailsFetchOptions = {},
): Promise<Record<string, unknown>> {
  const trimmed = typeof identifier === 'string' ? identifier.trim() : '';
  if (trimmed.length === 0) {
    throw new FundingTendersRequestError('INVALID_ARGUMENT', 'topicDetails identifier must be a non-empty string.');
  }
  const timeoutMs = options.timeoutMs ?? DETAIL_TIMEOUT_MS;
  const maxRetries = options.maxRetries ?? DETAIL_MAX_RETRIES;
  const prefix = options.urlPrefix ?? TOPIC_DETAILS_URL_PREFIX;
  const doFetch = options.fetchImpl ?? fetch;
  const url = `${prefix}${encodeURIComponent(trimmed.toLowerCase())}.json`;

  let lastError: FundingTendersRequestError | null = null;
  for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
    if (attempt > 0) {
      await sleep(500);
    }
    try {
      const response = await doFetch(url, {
        method: 'GET',
        headers: {
          accept: 'application/json',
          'user-agent': 'adminiculum-opportunity-watcher/0.1 (bounded manual dry-run; internal)',
        },
        signal: AbortSignal.timeout(timeoutMs),
      });
      const declaredLength = Number(response.headers.get('content-length') ?? '0');
      if (declaredLength > DETAIL_MAX_RESPONSE_BYTES) {
        throw new FundingTendersRequestError('SIZE_EXCEEDED', 'topicDetails response exceeds the bounded size limit.');
      }
      const text = await response.text();
      if (text.length > DETAIL_MAX_RESPONSE_BYTES) {
        throw new FundingTendersRequestError('SIZE_EXCEEDED', 'topicDetails response exceeds the bounded size limit.');
      }
      if (!response.ok) {
        const err = new FundingTendersRequestError('HTTP_ERROR', `topicDetails request failed with HTTP ${response.status}.`, response.status);
        lastError = err;
        if (RETRYABLE_HTTP.has(response.status)) {
          continue;
        }
        throw err;
      }
      let parsed: unknown;
      try {
        parsed = JSON.parse(text);
      } catch {
        throw new FundingTendersRequestError('MALFORMED_RESPONSE', 'topicDetails response is not valid JSON.');
      }
      if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
        throw new FundingTendersRequestError('MALFORMED_RESPONSE', 'topicDetails response is not a JSON object.');
      }
      return parsed as Record<string, unknown>;
    } catch (error) {
      if (error instanceof FundingTendersRequestError) {
        if (error.code === 'HTTP_ERROR' && error.status !== null && RETRYABLE_HTTP.has(error.status)) {
          lastError = error;
          continue;
        }
        throw error;
      }
      const name = error instanceof Error ? error.name : 'Unknown';
      if (name === 'TimeoutError' || name === 'AbortError') {
        lastError = new FundingTendersRequestError('TIMEOUT', `topicDetails request timed out after ${timeoutMs} ms.`);
        continue;
      }
      lastError = new FundingTendersRequestError('NETWORK_ERROR', 'topicDetails request failed: network error.');
      continue;
    }
  }
  throw lastError ?? new FundingTendersRequestError('RETRIES_EXHAUSTED', 'topicDetails request failed after all retry attempts.');
}
