export const CLIENT_PORTAL_FEATURE = 'CLIENT_PORTAL' as const;
export const CLIENT_PORTAL_NOT_ENABLED_REASON = 'CLIENT_PORTAL_NOT_ENABLED' as const;

export const CLIENT_PORTAL_ENABLE_FLAG = 'ENABLE_CLIENT_PORTAL' as const;
export const CLIENT_PORTAL_OWNERSHIP_MODEL_FLAG = 'ENABLE_CLIENT_PORTAL_OWNERSHIP_MODEL' as const;
export const CLIENT_PORTAL_RUNTIME_READY_FLAG = 'ENABLE_CLIENT_PORTAL_RUNTIME_READY' as const;

export type ClientPortalFeature = typeof CLIENT_PORTAL_FEATURE;
export type ClientPortalUnavailableReason = typeof CLIENT_PORTAL_NOT_ENABLED_REASON;
