// ============================================================================
// REHYDRATION — restore original values from the confidential mapping.
// ============================================================================
//
// This is a pure, isolated helper (no database, no file I/O, no network) so it
// can be unit-tested independently of the live anonymize service. The mapping is
// the `original → replacement` correspondence recorded during pseudonymization;
// it must never be included in an external AI handoff.

/** One redaction entry: the token that replaced a value and the original value. */
export interface RehydrationItem {
  replacement: string;
  original: string;
}

export interface RehydrationWarning {
  token: string;
  reason: string;
  original?: string;
}

export interface RehydrationResult {
  success: boolean;
  rehydratedContent: string | null;
  rehydrationStatus: 'COMPLETE' | 'PARTIAL' | 'FAILED';
  warnings: RehydrationWarning[];
  totalTokens: number;
  resolvedTokens: number;
  unresolvedTokens: number;
  error?: string;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Restore original values into an external AI response.
 *
 * Placeholders generated by the anonymizer carry Hungarian accented characters
 * and, occasionally, internal spaces (`[AZONOSÍTÓ_1]`, `[CÍM_1]`, `[MEGBÍZÓ]`,
 * `[ELLENÉRDEKŰ FÉL]`). Matching must therefore accept any bracketed token
 * (without nested brackets or newlines), never a narrow `[A-Z0-9_]` pattern
 * which silently skips accented tokens.
 *
 * Safety properties:
 * - repeated placeholders resolve consistently via a single token map;
 * - unknown placeholders are left visibly unresolved and reported, never deleted;
 * - a malformed/empty response never crashes (it returns a FAILED result);
 * - `[SZEMÉLY_1]` is never treated as a prefix of `[SZEMÉLY_10]` because each
 *   replacement targets the full bracketed token including its closing bracket.
 */
export function rehydrateDocument(
  aiResponseText: string,
  redactedItems: RehydrationItem[]
): RehydrationResult {
  if (!aiResponseText || aiResponseText.trim().length === 0) {
    return {
      success: false,
      rehydratedContent: null,
      rehydrationStatus: 'FAILED',
      warnings: [{ token: '', reason: 'AI response text is empty' }],
      totalTokens: redactedItems.length,
      resolvedTokens: 0,
      unresolvedTokens: redactedItems.length,
      error: 'AI response text is empty',
    };
  }

  if (!redactedItems || redactedItems.length === 0) {
    return {
      success: true,
      rehydratedContent: aiResponseText,
      rehydrationStatus: 'COMPLETE',
      warnings: [],
      totalTokens: 0,
      resolvedTokens: 0,
      unresolvedTokens: 0,
    };
  }

  const warnings: RehydrationWarning[] = [];
  let resolvedCount = 0;
  let unresolvedCount = 0;

  // Build a map of replacement -> original for fast lookup.
  // Key is the normalized replacement token (e.g. "[AZONOSÍTÓ_1]", "[MEGBÍZÓ]").
  const tokenMap = new Map<string, string>();
  for (const item of redactedItems) {
    const normalizedReplacement = item.replacement.toUpperCase().trim();
    tokenMap.set(normalizedReplacement, item.original);
  }

  const placeholderRegex = /\[([^\[\]\r\n]+)\]/g;

  let result = aiResponseText;
  let match: RegExpExecArray | null;

  const resolvedTokens = new Set<string>();

  // A bracket token is treated as one of ours if it carries an index suffix
  // (`_1`), a Hungarian accented uppercase letter, or an internal space — the
  // shapes produced by the anonymizer. This avoids flagging arbitrary bracketed
  // text (citations like [1], [abc], [link]) as unresolved placeholders.
  const looksLikeKnownToken = (key: string): boolean =>
    key.includes('_') || /[ÁÉÍÓÖŐÚÜŰ]/.test(key) || key.includes(' ');

  // First pass: replace every known placeholder with its original value.
  while ((match = placeholderRegex.exec(aiResponseText)) !== null) {
    const placeholder = match[0];
    const tokenKey = match[1].toUpperCase().trim();
    const normalizedKey = `[${tokenKey}]`;
    const original = tokenMap.get(normalizedKey);

    if (original !== undefined) {
      result = result.replace(new RegExp(escapeRegex(placeholder), 'g'), original);
      resolvedTokens.add(normalizedKey);
      resolvedCount++;
    } else if (looksLikeKnownToken(tokenKey)) {
      warnings.push({
        token: placeholder,
        reason: 'Token not found in mapping',
        original: undefined,
      });
      unresolvedCount++;
    }
  }

  // Second pass: defensively report any of our own redaction replacements that
  // are still present in the output (e.g. produced by a partial or malformed
  // external response), so they are surfaced rather than silently dropped.
  for (const item of redactedItems) {
    const normalizedReplacement = item.replacement.toUpperCase().trim();

    if (!resolvedTokens.has(normalizedReplacement)) {
      if (result.toUpperCase().includes(normalizedReplacement)) {
        warnings.push({
          token: item.replacement,
          reason: 'Placeholder still present in output - could not resolve',
          original: item.original,
        });
        unresolvedCount++;
        resolvedTokens.add(normalizedReplacement);
      }
    }
  }

  let status: 'COMPLETE' | 'PARTIAL' | 'FAILED';
  if (unresolvedCount === 0) {
    status = 'COMPLETE';
  } else if (resolvedCount > 0) {
    status = 'PARTIAL';
  } else {
    status = 'FAILED';
  }

  return {
    success: status !== 'FAILED',
    rehydratedContent: result,
    rehydrationStatus: status,
    warnings,
    totalTokens: redactedItems.length,
    resolvedTokens: resolvedCount,
    unresolvedTokens: unresolvedCount,
  };
}
