import { ComplianceProposalKind } from '@prisma/client';

export const COMPLIANCE_ACTION_INTENTS = {
  REMEDIATE_COMPLIANCE_GAP: 'REMEDIATE_COMPLIANCE_GAP',
  DISCLOSE_REQUIREMENT: 'DISCLOSE_REQUIREMENT',
  UPDATE_DOCUMENTATION: 'UPDATE_DOCUMENTATION',
  IMPLEMENT_CONTROL: 'IMPLEMENT_CONTROL',
  REVIEW_APPLICABILITY: 'REVIEW_APPLICABILITY',
  ADDRESS_OPEN_MATTER: 'ADDRESS_OPEN_MATTER',
} as const;

export type ComplianceActionIntentKey = typeof COMPLIANCE_ACTION_INTENTS[keyof typeof COMPLIANCE_ACTION_INTENTS];

export const ACTION_INTENT_BY_KIND: Record<ComplianceProposalKind, ComplianceActionIntentKey> = {
  REMEDIATION: COMPLIANCE_ACTION_INTENTS.REMEDIATE_COMPLIANCE_GAP,
  DISCLOSURE: COMPLIANCE_ACTION_INTENTS.DISCLOSE_REQUIREMENT,
  DOCUMENT_UPDATE: COMPLIANCE_ACTION_INTENTS.UPDATE_DOCUMENTATION,
  CONTROL_IMPLEMENTATION: COMPLIANCE_ACTION_INTENTS.IMPLEMENT_CONTROL,
  REVIEW: COMPLIANCE_ACTION_INTENTS.REVIEW_APPLICABILITY,
  OPEN_MATTER: COMPLIANCE_ACTION_INTENTS.ADDRESS_OPEN_MATTER,
};

export const COMPLIANCE_PROPOSAL_KINDS = Object.keys(ACTION_INTENT_BY_KIND) as ComplianceProposalKind[];
export const COMPLIANCE_ACTION_INTENT_KEYS = Object.values(COMPLIANCE_ACTION_INTENTS);

export function isCompatibleActionIntent(kind: ComplianceProposalKind, actionIntentKey: string): boolean {
  return ACTION_INTENT_BY_KIND[kind] === actionIntentKey;
}
